# D022: CRIE UM PROGRAMA QUE LEIA ONOME COMPLETO DE UMA PESSOA E MOSTRE:

# - O NOME COM TODAS AS LETRAS MAIÚSCULAS
# - O NOME COM TODAS MINÚSCULAS
# - QUANTAS LETRAS AO TODO (SEM CONSIDERAR ESPAÇOS)
# - QUANTAS LETRAS TEM O PRIMEIRO NOME